import tensorflow as tf
import numpy as np
import os
import cv2

MODEL_PATH = "models/fruitfly_fomo.h5"
DATASET_DIR = "dataset/train" 
OUTPUT_HEADER = "../model_data.h"          
OUTPUT_TFLITE = "models/fruitfly_fomo_quant.tflite" 
IMG_SIZE = 96

if not os.path.exists(MODEL_PATH):
    print(f"[ERROR] Model not found. Run training.py first.")
    exit()

# --- CRITICAL FIX: compile=False ---
# This prevents the "Unknown loss function" error
print("[INFO] Loading Keras model...")
model = tf.keras.models.load_model(MODEL_PATH, compile=False)

def representative_dataset_gen():
    files = [f for f in os.listdir(DATASET_DIR) if f.endswith(('.jpg', '.png', '.jpeg'))]
    for file_name in files[:100]: 
        img = cv2.imread(os.path.join(DATASET_DIR, file_name))
        if img is None: continue
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
        img = img.astype(np.float32) / 255.0
        img = np.expand_dims(img, axis=0)
        yield [img]

print("[INFO] Converting to INT8 TFLite...")
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

tflite_model = converter.convert()

with open(OUTPUT_TFLITE, "wb") as f:
    f.write(tflite_model)
print(f"[SUCCESS] Saved {OUTPUT_TFLITE}")

# Generate Header for STM32
def create_header(data, var_name):
    header = f"/* Generated by convert_to_tflite.py */\n"
    header += f"#ifndef MODEL_DATA_H\n#define MODEL_DATA_H\n\n"
    header += f"#include <stdint.h>\n\n"
    header += f"alignas(16) const unsigned char {var_name}[] = {{\n  "
    for i, byte in enumerate(data):
        header += f"0x{byte:02x}, "
        if (i + 1) % 12 == 0: header += "\n  "
    header += "\n};\n\n"
    header += f"const int {var_name}_len = {len(data)};\n"
    header += f"#endif\n"
    return header

print(f"[INFO] Writing {OUTPUT_HEADER}...")
with open(OUTPUT_HEADER, "w") as f:
    f.write(create_header(tflite_model, "fruitfly_fomo_model"))

print("[SUCCESS] Header file generated.")