import tensorflow as tf
import numpy as np
import os
import cv2

# --- CONFIG ---
MODEL_PATH = "models/plant_diseases_mobilenet.h5"
TFLITE_PATH = "models/plant_diseases_mobilenet_quant.tflite"
HEADER_PATH = "../model_data.h"
# We use the train folder for calibration since we don't have a dedicated test folder
DATASET_DIR = "dataset/train" 
IMG_SIZE = 96

if not os.path.exists(MODEL_PATH):
    print("[ERROR] Model not found. Run training.py first.")
    exit()

# --- REPRESENTATIVE DATASET GENERATOR ---
def representative_dataset_gen():
    # Iterate through subfolders
    count = 0
    for root, dirs, files in os.walk(DATASET_DIR):
        for file in files:
            if file.lower().endswith(('.png', '.jpg', '.jpeg')):
                img_path = os.path.join(root, file)
                img = cv2.imread(img_path)
                if img is None: continue
                
                img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
                img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
                img = img.astype(np.float32)
                # Note: The model has Rescaling layer inside, so we feed 0-255 float
                img = np.expand_dims(img, axis=0)
                yield [img]
                
                count += 1
                if count >= 100: return

print("[INFO] Loading Model...")
# compile=False avoids issues if custom optimizers were used
model = tf.keras.models.load_model(MODEL_PATH, compile=False)

print("[INFO] Converting to TFLite (INT8)...")
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
# Ensure full integer quantization for MCU compatibility
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

tflite_model = converter.convert()

with open(TFLITE_PATH, "wb") as f:
    f.write(tflite_model)
print(f"[SUCCESS] TFLite saved: {TFLITE_PATH}")

# --- HEX DUMP ---
def create_header(data, var_name):
    header = f"/* Generated by convert.py */\n"
    header += f"#ifndef MODEL_DATA_H\n#define MODEL_DATA_H\n\n"
    header += f"#include <stdint.h>\n\n"
    header += f"alignas(16) const unsigned char {var_name}[] = {{\n  "
    for i, byte in enumerate(data):
        header += f"0x{byte:02x}, "
        if (i + 1) % 12 == 0: header += "\n  "
    header += "\n};\n\n"
    header += f"const int {var_name}_len = {len(data)};\n"
    header += f"#endif\n"
    return header

with open(HEADER_PATH, "w") as f:
    f.write(create_header(tflite_model, "mobilenet_model"))
print(f"[SUCCESS] C Header saved: {HEADER_PATH}")