#include "lib_model.h"
#include "mbed.h"

#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

// -------------------------------------------------------------------------
// 1. Configuration and Globals
// -------------------------------------------------------------------------

// Increased to 215KB. ResNet on 32x32x3 requires significant RAM.
// STM32F746 has ~320KB SRAM. 215KB for Arena + ~100KB for OS/Stack is the limit.
const int kTensorArenaSize = 215 * 1024; 
static uint8_t tensor_arena[kTensorArenaSize] __attribute__((aligned(16)));

static tflite::MicroMutableOpResolver<40> resolver; // Increased op capacity

static tflite::MicroInterpreter* interpreter = nullptr;
static TfLiteTensor* input_tensor = nullptr;
static TfLiteTensor* output_tensor = nullptr;
static const tflite::Model* model = nullptr;

// -------------------------------------------------------------------------
// 2. Model Initialization Function
// -------------------------------------------------------------------------
int InitModel(const unsigned char* model_data, uint8_t* optional_arena_ptr, int optional_size) {
    
    // A. Load Model
    model = tflite::GetModel(model_data);
    if (model->version() != TFLITE_SCHEMA_VERSION) {
        printf("[ERROR] Model Schema Version Mismatch!\r\n");
        return MODEL_ERROR;
    }

    // B. Register Operators (Comprehensive list for ResNet)
    resolver.AddConv2D();
    resolver.AddDepthwiseConv2D();
    resolver.AddFullyConnected();
    resolver.AddSoftmax();
    resolver.AddRelu();
    resolver.AddRelu6();
    resolver.AddAveragePool2D();
    resolver.AddMaxPool2D();
    resolver.AddMean(); 
    resolver.AddAdd();
    resolver.AddSub();
    resolver.AddMul();
    resolver.AddReshape();
    resolver.AddShape();          
    resolver.AddStridedSlice();   
    resolver.AddPack();
    resolver.AddUnpack();
    resolver.AddConcatenation();
    resolver.AddSplit();
    resolver.AddPad();            
    resolver.AddResizeNearestNeighbor();
    // Extra ops that might be generated by Keras
    resolver.AddCast();
    resolver.AddFloor();
    resolver.AddGreater();
    resolver.AddLess();

    // C. Initialize Interpreter
    static tflite::MicroInterpreter static_interpreter(
        model, resolver, tensor_arena, kTensorArenaSize
    );
    interpreter = &static_interpreter;

    // D. Allocate Tensors
    TfLiteStatus allocate_status = interpreter->AllocateTensors();
    if (allocate_status != kTfLiteOk) {
        // Critical: Print this error to understand why LED blinks
        printf("[ERROR] AllocateTensors() Failed! Arena size: %d bytes.\r\n", kTensorArenaSize);
        // It will likely print "Arena too small" or "Missing Op" in the console.
        return MODEL_ERROR;
    }

    // E. Get Input/Output Pointers
    input_tensor = interpreter->input(0);
    output_tensor = interpreter->output(0);

    // Print successful init (Safe, happens before loop)
    printf("[INFO] Model Init OK. Input: %d x %d x %d\r\n", 
           input_tensor->dims->data[1], input_tensor->dims->data[2], input_tensor->dims->data[3]);

    return MODEL_OK;
}

// -------------------------------------------------------------------------
// 3. Inference Function
// -------------------------------------------------------------------------
int RunInference(float* input_data, float* output_data) {
    if (interpreter == nullptr) return MODEL_ERROR;

    // A. Copy Input Data
    if (input_tensor->type == kTfLiteFloat32) {
        for (int i = 0; i < input_tensor->bytes / sizeof(float); i++) {
            input_tensor->data.f[i] = input_data[i];
        }
    } else {
        return MODEL_ERROR; 
    }

    // B. Invoke Inference
    TfLiteStatus invoke_status = interpreter->Invoke();
    if (invoke_status != kTfLiteOk) {
        return MODEL_ERROR;
    }

    // C. Copy Output Data
    if (output_tensor->type == kTfLiteFloat32) {
        for (int i = 0; i < output_tensor->bytes / sizeof(float); i++) {
            output_data[i] = output_tensor->data.f[i];
        }
    } else {
        return MODEL_ERROR;
    }

    return MODEL_OK;
}